name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Test Extension Build
        run: |
          # Install vsce for testing
          npm install -g @vscode/vsce

          # Test packaging the extension
          vsce package --out test-extension.vsix

          # Verify the package was created
          ls -la test-extension.vsix

          # Clean up
          rm test-extension.vsix

      - name: Validate package.json
        run: |
          # Check that package.json is valid
          node -e "JSON.parse(require('fs').readFileSync('package.json', 'utf8'))"

          # Check that extension.js exists and is valid JavaScript
          node -c extension.js